"""Command-line interface: the primary, reproducible way to run every analysis.

Every subcommand takes an explicit ``--seed`` and prints deterministic output, so any
number quoted in the README can be regenerated by pasting the command next to it. The
notebook is a demonstration layer on top of these same functions; it is not where results
come from.
"""

from __future__ import annotations

import argparse
import math
from collections.abc import Sequence

from ab_testing_kit.design import analytic_power, mde, sample_size, validate_power
from ab_testing_kit.peeking import peeking_study, type_i_error_curve
from ab_testing_kit.sequential import (
    SPENDING_FUNCTIONS,
    sequential_design,
    sequential_error_curve,
    sequential_study,
)
from ab_testing_kit.simulation import ExperimentSpec, SimulationSummary

__all__ = ["main"]


def _spec_from_args(args: argparse.Namespace, n_per_arm: int, effect: float) -> ExperimentSpec:
    return ExperimentSpec(
        n_per_arm=n_per_arm,
        metric=args.metric,
        baseline=args.baseline,
        effect=effect,
        sd=args.sd,
    )


def _add_metric_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--metric", choices=("binary", "continuous"), required=True, help="Metric type."
    )
    parser.add_argument(
        "--baseline", type=float, required=True, help="Control conversion rate or mean."
    )
    parser.add_argument(
        "--sd", type=float, default=1.0, help="Within-arm SD (continuous only). Default 1.0."
    )
    parser.add_argument("--alpha", type=float, default=0.05, help="Two-sided alpha. Default 0.05.")


def _add_sim_args(parser: argparse.ArgumentParser, default_sims: int) -> None:
    parser.add_argument(
        "--sims", type=int, default=default_sims, help=f"Replications. Default {default_sims}."
    )
    parser.add_argument("--seed", type=int, default=0, help="Master seed. Default 0.")


def _cmd_design(args: argparse.Namespace) -> int:
    n = sample_size(
        args.metric, args.baseline, args.mde, sd=args.sd, alpha=args.alpha, power=args.power
    )
    achieved = analytic_power(args.metric, args.baseline, args.mde, n, sd=args.sd, alpha=args.alpha)
    print(f"metric               {args.metric}")
    print(f"baseline             {args.baseline:g}")
    if args.metric == "continuous":
        print(f"within-arm sd        {args.sd:g}")
    print(f"absolute MDE         {args.mde:g}")
    if args.metric == "binary":
        print(f"relative MDE         {args.mde / args.baseline:.1%}")
    print(f"alpha (two-sided)    {args.alpha:g}")
    print(f"target power         {args.power:.0%}")
    print()
    print(f"n per arm            {n:,}")
    print(f"total n              {2 * n:,}")
    print(f"power at that n      {achieved:.4f}")
    return 0


def _cmd_mde(args: argparse.Namespace) -> int:
    detectable = mde(
        args.metric, args.baseline, args.n, sd=args.sd, alpha=args.alpha, power=args.power
    )
    print(f"metric               {args.metric}")
    print(f"baseline             {args.baseline:g}")
    print(f"n per arm            {args.n:,}")
    print(f"alpha (two-sided)    {args.alpha:g}")
    print(f"target power         {args.power:.0%}")
    print()
    print(f"absolute MDE         {detectable:.6g}")
    if args.metric == "binary":
        print(f"relative MDE         {detectable / args.baseline:.2%}")
    return 0


def _cmd_validate_power(args: argparse.Namespace) -> int:
    spec = _spec_from_args(args, args.n, args.effect)
    check = validate_power(spec, n_sims=args.sims, seed=args.seed, alpha=args.alpha)
    lo, hi = check.simulated.reject_rate_ci
    print(f"metric               {args.metric}")
    print(f"baseline             {args.baseline:g}")
    print(f"true effect          {args.effect:g}")
    print(f"n per arm            {args.n:,}")
    print(f"replications         {args.sims:,}  (seed {args.seed})")
    print()
    print(f"analytic power       {check.analytic:.4f}")
    print(f"simulated power      {check.simulated.reject_rate:.4f}  95% CI [{lo:.4f}, {hi:.4f}]")
    print(f"gap (sim - analytic) {check.gap:+.4f}")
    print(f"formula inside CI    {'yes' if check.agrees else 'no'}")
    return 0


def _print_study_preamble(args: argparse.Namespace, extra: tuple[str, str] | None = None) -> None:
    """Header shared by the peeking and sequential tables, so the two line up on the page."""
    print(f"metric               {args.metric}")
    print(f"baseline             {args.baseline:g}")
    print(
        f"true effect          {args.effect:g}   ({'null' if args.effect == 0 else 'alternative'})"
    )
    print(f"n per arm (horizon)  {args.n:,}")
    print(f"alpha (two-sided)    {args.alpha:g}")
    if extra is not None:
        print(f"{extra[0]:<20} {extra[1]}")
    print(f"replications         {args.sims:,}  (seed {args.seed}, shared across all rows)")
    print()


def _print_study_table(label: str, rows: dict[int, SimulationSummary]) -> None:
    """One row per look count, identical in shape for the naive and the corrected rule.

    ``est. bias`` is signed and ``mean |est|`` is not, and both are needed: under a two-sided
    null the signed bias cancels to zero however inflated the individual estimates are, so
    the magnitude column is the one that shows the winner's curse there. Both are taken over
    the replications that rejected.
    """
    header = (
        f"{'looks':>6}  {label:>13}  {'95% CI':>18}  "
        f"{'mean n at stop':>15}  {'est. bias':>10}  {'mean |est|':>10}"
    )
    print(header)
    print("-" * len(header))
    for k, summary in rows.items():
        lo, hi = summary.reject_rate_ci
        print(
            f"{k:>6}  {summary.reject_rate:>13.4f}  [{lo:>7.4f}, {hi:>7.4f}]  "
            f"{summary.mean_n_per_arm:>15,.0f}  {summary.estimate_bias:>+10.4f}  "
            f"{summary.mean_abs_estimate:>10.4f}"
        )


def _cmd_peeking(args: argparse.Namespace) -> int:
    spec = _spec_from_args(args, args.n, args.effect)
    _print_study_preamble(args)
    rows = {
        k: (
            type_i_error_curve(
                spec, look_counts=(k,), n_sims=args.sims, seed=args.seed, alpha=args.alpha
            )[k]
            if args.effect == 0.0
            else peeking_study(spec, k, n_sims=args.sims, seed=args.seed, alpha=args.alpha)
        )
        for k in args.looks
    }
    _print_study_table("Type-I error" if args.effect == 0.0 else "power", rows)
    return 0


def _cmd_sequential(args: argparse.Namespace) -> int:
    spec = _spec_from_args(args, args.n, args.effect)
    _print_study_preamble(args, extra=("spending function", args.spending))
    rows = {
        k: (
            sequential_error_curve(
                spec,
                look_counts=(k,),
                n_sims=args.sims,
                seed=args.seed,
                alpha=args.alpha,
                spending=args.spending,
            )[k]
            if args.effect == 0.0
            else sequential_study(
                spec,
                k,
                n_sims=args.sims,
                seed=args.seed,
                alpha=args.alpha,
                spending=args.spending,
            )
        )
        for k in args.looks
    }
    _print_study_table("Type-I error" if args.effect == 0.0 else "power", rows)
    return 0


def _cmd_boundary(args: argparse.Namespace) -> int:
    design = sequential_design(args.n, args.looks, alpha=args.alpha, spending=args.spending)
    boundary = design.boundary
    print(f"n per arm (horizon)  {args.n:,}")
    print(f"looks requested      {args.looks}")
    print(f"alpha (two-sided)    {args.alpha:g}")
    print(f"spending function    {args.spending}")
    print()
    header = (
        f"{'look':>5}  {'n per arm':>10}  {'information':>11}  "
        f"{'critical z':>10}  {'alpha here':>11}  {'cumulative':>11}"
    )
    print(header)
    print("-" * len(header))
    rows = zip(
        design.schedule,
        boundary.information,
        boundary.z,
        boundary.increments,
        boundary.achieved,
        strict=True,
    )
    for i, (n, t, z, step, total) in enumerate(rows, start=1):
        critical = "     never" if math.isinf(z) else f"{z:>10.4f}"
        print(f"{i:>5}  {n:>10,}  {t:>11.4f}  {critical}  {step:>11.3e}  {total:>11.6f}")
    print()
    print(f"total alpha spent    {boundary.total_alpha:.6f}  (target {args.alpha:g})")
    return 0


def _add_spending_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--spending",
        choices=tuple(SPENDING_FUNCTIONS),
        default="obrien-fleming",
        help="Alpha spending function. Default obrien-fleming.",
    )


def _looks(value: str) -> tuple[int, ...]:
    try:
        parsed = tuple(int(part) for part in value.split(","))
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"expected comma-separated integers, got {value!r}"
        ) from exc
    if not parsed or any(k < 1 for k in parsed):
        raise argparse.ArgumentTypeError(f"look counts must all be >= 1, got {value!r}")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ab-testing-kit",
        description="Experiment design and analysis, with every claim checked by simulation.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_design = sub.add_parser("design", help="Sample size required to detect an effect.")
    _add_metric_args(p_design)
    p_design.add_argument("--mde", type=float, required=True, help="Absolute effect to detect.")
    p_design.add_argument("--power", type=float, default=0.80, help="Target power. Default 0.80.")
    p_design.set_defaults(func=_cmd_design)

    p_mde = sub.add_parser("mde", help="Smallest effect detectable at a given sample size.")
    _add_metric_args(p_mde)
    p_mde.add_argument("--n", type=int, required=True, help="Units per arm.")
    p_mde.add_argument("--power", type=float, default=0.80, help="Target power. Default 0.80.")
    p_mde.set_defaults(func=_cmd_mde)

    p_val = sub.add_parser(
        "validate-power", help="Simulate at a given n and compare against the formula."
    )
    _add_metric_args(p_val)
    p_val.add_argument("--n", type=int, required=True, help="Units per arm.")
    p_val.add_argument("--effect", type=float, required=True, help="True absolute effect.")
    _add_sim_args(p_val, 10_000)
    p_val.set_defaults(func=_cmd_validate_power)

    p_peek = sub.add_parser(
        "peeking", help="Error rate as a function of how often the experiment is checked."
    )
    _add_metric_args(p_peek)
    p_peek.add_argument("--n", type=int, required=True, help="Planned units per arm.")
    p_peek.add_argument(
        "--effect", type=float, default=0.0, help="True absolute effect. Default 0.0 (the null)."
    )
    p_peek.add_argument(
        "--looks",
        type=_looks,
        default=(1, 2, 3, 5, 10, 20),
        help="Comma-separated look counts. Default 1,2,3,5,10,20.",
    )
    _add_sim_args(p_peek, 10_000)
    p_peek.set_defaults(func=_cmd_peeking)

    p_seq = sub.add_parser(
        "sequential", help="The same schedule of looks, with the alpha budget enforced."
    )
    _add_metric_args(p_seq)
    p_seq.add_argument("--n", type=int, required=True, help="Planned units per arm.")
    p_seq.add_argument(
        "--effect", type=float, default=0.0, help="True absolute effect. Default 0.0 (the null)."
    )
    p_seq.add_argument(
        "--looks",
        type=_looks,
        default=(1, 2, 3, 5, 10, 20),
        help="Comma-separated look counts. Default 1,2,3,5,10,20.",
    )
    _add_spending_arg(p_seq)
    _add_sim_args(p_seq, 10_000)
    p_seq.set_defaults(func=_cmd_sequential)

    p_bound = sub.add_parser(
        "boundary", help="Print the critical values and the alpha each look consumes."
    )
    p_bound.add_argument("--n", type=int, required=True, help="Planned units per arm.")
    p_bound.add_argument("--looks", type=int, required=True, help="Number of analyses.")
    p_bound.add_argument("--alpha", type=float, default=0.05, help="Two-sided alpha. Default 0.05.")
    _add_spending_arg(p_bound)
    p_bound.set_defaults(func=_cmd_boundary)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.func(args))
    except ValueError as exc:
        print(f"error: {exc}")
        return 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
