"""Command-line interface: the primary, reproducible way to run every analysis.

Every subcommand takes an explicit ``--seed`` and prints deterministic output, so any
number quoted in the README can be regenerated by pasting the command next to it. The
notebook is a demonstration layer on top of these same functions; it is not where results
come from.
"""

from __future__ import annotations

import argparse
from collections.abc import Sequence

from ab_testing_kit.design import analytic_power, mde, sample_size, validate_power
from ab_testing_kit.peeking import peeking_study, type_i_error_curve
from ab_testing_kit.simulation import ExperimentSpec

__all__ = ["main"]


def _spec_from_args(args: argparse.Namespace, n_per_arm: int, effect: float) -> ExperimentSpec:
    return ExperimentSpec(
        n_per_arm=n_per_arm,
        metric=args.metric,
        baseline=args.baseline,
        effect=effect,
        sd=args.sd,
    )


def _add_metric_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--metric", choices=("binary", "continuous"), required=True, help="Metric type."
    )
    parser.add_argument(
        "--baseline", type=float, required=True, help="Control conversion rate or mean."
    )
    parser.add_argument(
        "--sd", type=float, default=1.0, help="Within-arm SD (continuous only). Default 1.0."
    )
    parser.add_argument("--alpha", type=float, default=0.05, help="Two-sided alpha. Default 0.05.")


def _add_sim_args(parser: argparse.ArgumentParser, default_sims: int) -> None:
    parser.add_argument(
        "--sims", type=int, default=default_sims, help=f"Replications. Default {default_sims}."
    )
    parser.add_argument("--seed", type=int, default=0, help="Master seed. Default 0.")


def _cmd_design(args: argparse.Namespace) -> int:
    n = sample_size(
        args.metric, args.baseline, args.mde, sd=args.sd, alpha=args.alpha, power=args.power
    )
    achieved = analytic_power(args.metric, args.baseline, args.mde, n, sd=args.sd, alpha=args.alpha)
    print(f"metric               {args.metric}")
    print(f"baseline             {args.baseline:g}")
    if args.metric == "continuous":
        print(f"within-arm sd        {args.sd:g}")
    print(f"absolute MDE         {args.mde:g}")
    if args.metric == "binary":
        print(f"relative MDE         {args.mde / args.baseline:.1%}")
    print(f"alpha (two-sided)    {args.alpha:g}")
    print(f"target power         {args.power:.0%}")
    print()
    print(f"n per arm            {n:,}")
    print(f"total n              {2 * n:,}")
    print(f"power at that n      {achieved:.4f}")
    return 0


def _cmd_mde(args: argparse.Namespace) -> int:
    detectable = mde(
        args.metric, args.baseline, args.n, sd=args.sd, alpha=args.alpha, power=args.power
    )
    print(f"metric               {args.metric}")
    print(f"baseline             {args.baseline:g}")
    print(f"n per arm            {args.n:,}")
    print(f"alpha (two-sided)    {args.alpha:g}")
    print(f"target power         {args.power:.0%}")
    print()
    print(f"absolute MDE         {detectable:.6g}")
    if args.metric == "binary":
        print(f"relative MDE         {detectable / args.baseline:.2%}")
    return 0


def _cmd_validate_power(args: argparse.Namespace) -> int:
    spec = _spec_from_args(args, args.n, args.effect)
    check = validate_power(spec, n_sims=args.sims, seed=args.seed, alpha=args.alpha)
    lo, hi = check.simulated.reject_rate_ci
    print(f"metric               {args.metric}")
    print(f"baseline             {args.baseline:g}")
    print(f"true effect          {args.effect:g}")
    print(f"n per arm            {args.n:,}")
    print(f"replications         {args.sims:,}  (seed {args.seed})")
    print()
    print(f"analytic power       {check.analytic:.4f}")
    print(f"simulated power      {check.simulated.reject_rate:.4f}  95% CI [{lo:.4f}, {hi:.4f}]")
    print(f"gap (sim - analytic) {check.gap:+.4f}")
    print(f"formula inside CI    {'yes' if check.agrees else 'no'}")
    return 0


def _cmd_peeking(args: argparse.Namespace) -> int:
    spec = _spec_from_args(args, args.n, args.effect)
    label = "Type-I error" if args.effect == 0.0 else "power"
    print(f"metric               {args.metric}")
    print(f"baseline             {args.baseline:g}")
    print(
        f"true effect          {args.effect:g}   ({'null' if args.effect == 0 else 'alternative'})"
    )
    print(f"n per arm (horizon)  {args.n:,}")
    print(f"alpha (two-sided)    {args.alpha:g}")
    print(f"replications         {args.sims:,}  (seed {args.seed}, shared across all rows)")
    print()
    header = f"{'looks':>6}  {label:>13}  {'95% CI':>18}  {'mean n at stop':>15}  {'est. bias':>10}"
    print(header)
    print("-" * len(header))
    for k in args.looks:
        summary = (
            type_i_error_curve(
                spec, look_counts=(k,), n_sims=args.sims, seed=args.seed, alpha=args.alpha
            )[k]
            if args.effect == 0.0
            else peeking_study(spec, k, n_sims=args.sims, seed=args.seed, alpha=args.alpha)
        )
        lo, hi = summary.reject_rate_ci
        bias = summary.estimate_bias
        print(
            f"{k:>6}  {summary.reject_rate:>13.4f}  [{lo:>7.4f}, {hi:>7.4f}]  "
            f"{summary.mean_n_per_arm:>15,.0f}  {bias:>+10.4f}"
        )
    return 0


def _looks(value: str) -> tuple[int, ...]:
    try:
        parsed = tuple(int(part) for part in value.split(","))
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"expected comma-separated integers, got {value!r}"
        ) from exc
    if not parsed or any(k < 1 for k in parsed):
        raise argparse.ArgumentTypeError(f"look counts must all be >= 1, got {value!r}")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ab-testing-kit",
        description="Experiment design and analysis, with every claim checked by simulation.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_design = sub.add_parser("design", help="Sample size required to detect an effect.")
    _add_metric_args(p_design)
    p_design.add_argument("--mde", type=float, required=True, help="Absolute effect to detect.")
    p_design.add_argument("--power", type=float, default=0.80, help="Target power. Default 0.80.")
    p_design.set_defaults(func=_cmd_design)

    p_mde = sub.add_parser("mde", help="Smallest effect detectable at a given sample size.")
    _add_metric_args(p_mde)
    p_mde.add_argument("--n", type=int, required=True, help="Units per arm.")
    p_mde.add_argument("--power", type=float, default=0.80, help="Target power. Default 0.80.")
    p_mde.set_defaults(func=_cmd_mde)

    p_val = sub.add_parser(
        "validate-power", help="Simulate at a given n and compare against the formula."
    )
    _add_metric_args(p_val)
    p_val.add_argument("--n", type=int, required=True, help="Units per arm.")
    p_val.add_argument("--effect", type=float, required=True, help="True absolute effect.")
    _add_sim_args(p_val, 10_000)
    p_val.set_defaults(func=_cmd_validate_power)

    p_peek = sub.add_parser(
        "peeking", help="Error rate as a function of how often the experiment is checked."
    )
    _add_metric_args(p_peek)
    p_peek.add_argument("--n", type=int, required=True, help="Planned units per arm.")
    p_peek.add_argument(
        "--effect", type=float, default=0.0, help="True absolute effect. Default 0.0 (the null)."
    )
    p_peek.add_argument(
        "--looks",
        type=_looks,
        default=(1, 2, 3, 5, 10, 20),
        help="Comma-separated look counts. Default 1,2,3,5,10,20.",
    )
    _add_sim_args(p_peek, 10_000)
    p_peek.set_defaults(func=_cmd_peeking)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.func(args))
    except ValueError as exc:
        print(f"error: {exc}")
        return 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
